apiVersion: v2
name: indexd
description: A Helm chart to package your application container for Kubernetes
# This will be updated with the release tag in the CI/CD pipeline before publishing. This has to be a valid semver for
# the linter to accept.
version: 0.0.1-replace
home: https://github.com/NCI-GDC/indexd/
maintainers:
  - name: Center for Translational Data Science
    email: cdis@uchicago.edu
    url: https://ctds.uchicago.edu
